### ISSUE TITLE
[BUG] pixelated enchant glints for shuri and bone knife

### ISSUE THREAD

**Issue by waifupngpl** [thomasglasser/Minejago#11]
**Describe the bug**
the glints are pixely instead of smooth

**To Reproduce**
1. get a bone knife or iron shuri
2. enchant them
3. in the hand, they are fine. throw them and look at them

**Expected behavior**
a normal smooth h igher res enchant glint

**Screenshots**
(https://www.youtube.com/watch?v=rpBI5YJ0_30&ab_channel=waifu_png_pl)

 - Loader [e.g. fabric, forge] fabric
 - Mod Version [e.g. 00e01a] this one
 - Minecraft Version [e.g. 1.19.3] this one

**Additional context**
inconsistency sucks

**Comment by thomasglasser** [comment]
It's not perfect but it does look a little better now.
