### ISSUE TITLE
Shuriken(s?) violently clitch out if missed [BUG]

### ISSUE THREAD

**Issue by Tir-Far-Thoinn** [thomasglasser/Minejago#12]
Shurkiens, if they hit the ground after they've started coming back to you, aggressively spasm.

1. Throw the shuriken into the air
2. Wait for it to come back to you
3. Dodge it
4. Look at where it hits the ground, and you should see it vibrating mid-air

**Expected behavior**
It should just hit the ground and get stuck normally

**Screenshots**
![image](https://user-images.githubusercontent.com/97119400/217494002-cf7616fa-4cae-49aa-9efe-c7e481612342.png)

.

**Comment by thomasglasser** [comment]
What loader(s) is this on? Forge, Fabric, or Quilt?
