### ISSUE TITLE
weirdness with the iron shuri again[BUG]

### ISSUE THREAD

**Issue by waifupngpl** [thomasglasser/Minejago#16]
**Describe the bug**
it defies gravity and weirdly resets mid air

**To Reproduce**
1. throw shuri (i threw it  somewhat high up that might have something to do with it)
2. wait for it to come back while moving away from the throwing location
3. its weird

**Expected behavior**
it just goes to the ground and stays there

**Screenshots**
https://youtu.be/S_kp8-yD424 

 - Loader [e.g. fabric, forge] fabric
 - Mod Version [e.g. 00e01a] the jar you gave us
 - Minecraft Version [e.g. 1.19.3] yes

**Additional context**
man these are really buggy eh

**Comment by thomasglasser** [comment]
> man these are really buggy eh

Yes 🥲

**Comment by thomasglasser** [comment]
I've not been able to reproduce this bug so I may have accidentally fixed it or it's just a very rare occurrence. I will reopen this issue if this is replicated in the future.
